name: CI/CD pipeline for flutter application
on:
  push:
    branches:
      - main 

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with: 
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        
      - name: Get dependencies
        run: flutter pub get
  
      
